name: Build

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ""
          draft: true
          prerelease: false
  windows:
    runs-on: windows-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build --release
          cp target/release/shutdown-on-lan.exe build/windows/shutdown-on-lan.exe
      - name: Package
        run: |
          cd build
          cd windows
          &"$Env:WIX\bin\candle.exe" Product.wxs
          &"$Env:WIX\bin\light.exe" Product.wixobj
          mv Product.msi shutdown-on-lan.msi
      - uses: actions/upload-artifact@v1
        with:
          name: shutdown-on-lan-windows.zip
          path: build/windows/shutdown-on-lan.msi
  mac:
    runs-on: macos-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build --release
      - name: Package
        run: |
          cd build/mac
          chmod +x build-installer.sh
          ./build-installer.sh
      - uses: actions/upload-artifact@v1
        with:
          name: shutdownonlan.pkg
          path: build/mac/shutdownonlan.pkg
